### ISSUE TITLE
Migrate to using bond0 on 10G

### ISSUE THREAD

**Issue by dstewen** [dstewen/talos-home#42]
I need to change the config on the MS-01 controllers so that it uses bonded interfaces instead of just a single 10G.

Currently using:

```
nodes:
  - hostname: "ms1"
    ipAddress: "192.168.10.51"
    installDiskSelector:
      serial: "1925E20E2038"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:cf:38"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:cf:39"
        ignore: true
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:cf:36"
        dhcp: false
        addresses:
          - "192.168.10.51/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.10.1"
        mtu: 1500
        vip:
          ip: "192.168.10.254"
```
